Build completed for the ustory OM-437ser
citron-hygiene-lp/salesforce pull request #105
Opened 2022-05-09 18:01 UTC by Citronhariom

Descriptions : Build completed for the   user tory OM-437ser

2022-05-09 22:12 UTC, MHigel commented
@Citronhariom it looks like your commit is missing the new Field Update metadata records that are needed by this Workflow.

2022-05-09 22:12 UTC, MHigel requested changes

2022-05-09 22:12 UTC, MHigel commented on force-app/main/default/workflows/Opportunity.workflow-meta.xml
> +        <actions>
These Field Updates are missing from the commit.

2022-05-10 10:19 UTC, Citronhariom commented on force-app/main/default/workflows/Opportunity.workflow-meta.xml
> +        <actions>
Hi @MHigel ,

Updated the file Please review it once let me know if any changes required from my side.

2022-05-10 22:38 UTC, MHigel commented
@Citronhariom there is a merge conflict on this file. Can you resolve it and recommit?

2022-05-17 13:09 UTC, Citronhariom commented
Hi @MHigel ,

The conflict has been resolved , Could you please review and let me know if anything required.

2022-05-17 18:21 UTC, darcy-old-git commented
Please submit a new PR

2022-05-17 18:21 UTC, closed without merging