OM-411
citron-hygiene-lp/salesforce pull request #106
Opened 2022-05-09 18:23 UTC by sidhartha-citron

2022-05-10 22:40 UTC, MHigel reviewed
@sidhartha-citron your change removes a number of existing values from the picklist.  Can you verify that this is intentional?  I don't see anything in the User Story's requirements that indicates this.

2022-05-10 22:40 UTC, MHigel requested changes

2022-05-10 22:40 UTC, MHigel commented on force-app/main/default/objects/Opportunity/recordTypes/UK.recordType-meta.xml
> -        <values>
Is removing these values intentional?

2022-05-11 03:09 UTC, sidhartha-citron commented on force-app/main/default/objects/Opportunity/recordTypes/UK.recordType-meta.xml
> -        <values>
Hi Matt . This PR contains LeadSource (OM-418) and Type (OM-411)picklistlist fields. I forgot to mention in description.

2022-05-11 23:33 UTC, merged