Build Completed for the user story:OM-388 V2
citron-hygiene-lp/salesforce pull request #136
Opened 2022-05-12 11:54 UTC by Citronhariom

Descriptions:  Created new PR for the OM- 388.

Please closed or discard my old PR  https://github.com/citron-hygiene-lp/salesforce/pull/76

2022-05-13 15:08 UTC, MHigel requested changes

2022-05-13 15:08 UTC, MHigel commented on force-app/main/default/classes/ManageRelatedContactFieldsTest.cls
> +            for(contact c : [SELECT Id,Account.Subsidiary__c FROM contact WHERE Id=:contact1.id]) {
Why are we using a `for` loop for this query?  Since the filter criteria only returns values where the record Id is `contact1.Id`, this will only ever return a single record. Since we're only dealing with a single Contact and a single Account, we're not able to actually validate the assertion for a scenario where the related `Account.Subsidiary__c` is not "CA".

2022-05-19 11:27 UTC, Citronhariom commented on force-app/main/default/classes/ManageRelatedContactFieldsTest.cls
> +            for(contact c : [SELECT Id,Account.Subsidiary__c FROM contact WHERE Id=:contact1.id]) {
Hi @MHigel ,
Updated the PR, Please review and let me know if anything required.

2022-05-19 11:39 UTC, rgoyalcitronhygiene commented
Approved after reviewing changes

2022-05-19 11:39 UTC, merged