OM-569
citron-hygiene-lp/salesforce pull request #173
Opened 2022-05-16 14:32 UTC by Citron-mohammad-Rafi

I have created PR for OM-569 and please review it and merge it.

2022-05-16 19:21 UTC, darcy-old-git requested changes
You cannot have <rules> then <fieldUpdates> and then back to <rules>. Metadata field types must be grouped together or this will not deploy.

2022-05-17 01:39 UTC, runicfox approved these changes

2022-05-19 13:52 UTC, Citron-mohammad-Rafi commented
@rgoyalcitronhygiene I made changes according to darcy's comment, please review it and merge it.

2022-05-24 09:58 UTC, rgoyalcitronhygiene commented
As per Offline discussion with Rafi, a new pull request will be raised by him.

2022-05-24 09:58 UTC, closed without merging