OM-571
citron-hygiene-lp/salesforce pull request #186
Opened 2022-05-17 16:11 UTC by Citron-mohammad-Rafi

Please review this PR and merge it.

2022-05-18 00:27 UTC, darcy-old-git requested changes
Please close and resubmit with the alerts and rules grouped with each other in the file

2022-05-18 00:27 UTC, darcy-old-git commented on force-app/main/default/workflows/Opportunity.workflow-meta.xml
> +    <alerts>
Alerts should not be in the middle of rules

2022-05-18 11:49 UTC, Citron-mohammad-Rafi commented on force-app/main/default/workflows/Opportunity.workflow-meta.xml
> +    <alerts>
@darcy-old-git I have resolved the issue according to your comment, Please review it and merge it. Now alert is not in midddle

2022-05-19 13:44 UTC, Citron-mohammad-Rafi commented on force-app/main/default/workflows/Opportunity.workflow-meta.xml
> +    <alerts>
@rgoyalcitronhygiene Please go through the comment and Please review this PR and merge it.

2022-05-24 09:16 UTC, rgoyalcitronhygiene approved these changes

2022-05-24 10:00 UTC, rgoyalcitronhygiene commented
As per offline discussion with Rafi, a new pull request will be raised

2022-05-24 10:00 UTC, closed without merging