Buid completed for the user story OM-384
citron-hygiene-lp/salesforce pull request #28
Opened 2022-04-25 11:01 UTC by Citronhariom

Descriptions - OM-384 build completed

2022-04-25 13:43 UTC, MHigel requested changes

2022-04-25 13:43 UTC, MHigel commented on force-app/main/default/objects/Opportunity/fields/Subsidiary__c.field-meta.xml
> +    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
@Citronhariom we'll want to set this value to "Treat blank fields as blanks" instead of zero.

2022-04-28 17:42 UTC, Citronhariom commented on force-app/main/default/objects/Opportunity/fields/Subsidiary__c.field-meta.xml
> +    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
Hi @MHigel  ,I already updated the PR .
Could you please approve the latest commit.

2022-04-28 17:42 UTC, Citronhariom commented on force-app/main/default/objects/Opportunity/fields/Subsidiary__c.field-meta.xml
> +    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
My latest  PR - https://github.com/citron-hygiene-lp/salesforce/pull/28/commits/b62580b95f6ccc966f4ccecc5bd626f3164194ee

2022-04-28 22:36 UTC, MHigel approved these changes

2022-04-28 22:36 UTC, merged