OM-229
citron-hygiene-lp/salesforce pull request #29
Opened 2022-04-25 11:52 UTC by Citron-mohammad-Rafi

2022-04-25 11:53 UTC, Citron-mohammad-Rafi commented
@MHigel Please review this PR if it is fine then merge it.

2022-04-25 14:15 UTC, MHigel requested changes
@Citron-mohammad-Rafi we need to move the `assignSubsidiary` method in the `beforeInsert` method to be the first method that's invoked so that the other methods that have logic relating to values in the `Subsidiary__c` field are able to correctly process the data point.

2022-04-25 15:01 UTC, Citron-mohammad-Rafi commented
@MHigel I have make changes according to comment please check. And merge it if everything is fine.

2022-04-28 17:50 UTC, MHigel requested changes

2022-04-28 17:51 UTC, MHigel approved these changes

2022-04-28 17:52 UTC, merged

2022-04-28 17:52 UTC, Citron-mohammad-Rafi commented on force-app/main/default/classes/ServiceTerritoryAssignmentTest.cls
> +        test.startTest();
@MHigel sure I will do it.