OM-230
citron-hygiene-lp/salesforce pull request #43
Opened 2022-04-26 15:29 UTC by Citron-mohammad-Rafi

@MHigel Please review this PR if it is fine then merge it.

2022-04-27 01:55 UTC, MHigel requested changes

2022-04-27 01:55 UTC, MHigel commented on force-app/main/default/classes/AccountParentValidationTest.cls
> +        insert account5;
Can we group the insertion of these individual account records into a collection and perform a single `insert` DML?

2022-04-27 01:55 UTC, MHigel commented on force-app/main/default/classes/AccountParentValidationTest.cls
> +                if(e.getMessage() != null || e.getMessage() != ''){
It would be better to have us assert the expected error message, rather than just that the message is blank.  Otherwise, if the transaction fails for a different reason, we won't know it.

2022-04-27 01:55 UTC, MHigel commented on force-app/main/default/classes/AccountParentValidationTest.cls
> +            Database.SaveResult accErrorList = Database.update(account1,false);
I would recommend changing the name of this collection to just `accError` since this variable is not a collection.

2022-04-27 01:55 UTC, MHigel commented on force-app/main/default/classes/AccountParentValidationTest.cls
> +            Database.SaveResult accErrorList2 = Database.update(account4,false);
Instead of instantiating a second `Database.SaveResult` variable, can we just use the existing `accError` from above?

2022-04-27 01:55 UTC, MHigel commented on force-app/main/default/classes/AccountParentValidationTest.cls
> +            Account acc = [Select isParent__c from Account where id =: account1.Id];
This variable is not used.  I think that we need to include an assert here that validates that `acc.IsParent__c` is true:

```
System.assert(acc.IsParent__c);
```

2022-04-27 01:55 UTC, MHigel commented on force-app/main/default/classes/AccountParentValidationTest.cls
> +            System.assertEquals(account5.ParentId,account1.Id);
We should also re-query the `account5` record since we've performed an `update` DML to ensure that the committed value of the record is correctly saved with an assert.

2022-04-27 05:04 UTC, Citron-mohammad-Rafi commented on force-app/main/default/classes/AccountParentValidationTest.cls
> +        insert account5;
@MHigel  Yes, we can insert accounts in the group but for one scenario we need to insert account with parent account for this we need to insert account first and then need to use it as parent.

2022-04-27 06:49 UTC, Citron-mohammad-Rafi commented on force-app/main/default/classes/AccountParentValidationTest.cls
> +        insert account5;
@MHigel Yes it is possible but for one scenario at the time insert account we need to assign a parent account so we need to insert one account as an individual.

2022-04-27 06:50 UTC, Citron-mohammad-Rafi commented on force-app/main/default/classes/AccountParentValidationTest.cls
> +                if(e.getMessage() != null || e.getMessage() != ''){
@MHigel, Okay I will do it. I will check condition based on message.

2022-04-27 06:50 UTC, Citron-mohammad-Rafi commented on force-app/main/default/classes/AccountParentValidationTest.cls
> +            Database.SaveResult accErrorList = Database.update(account1,false);
okay i will update.

2022-04-27 06:51 UTC, Citron-mohammad-Rafi commented on force-app/main/default/classes/AccountParentValidationTest.cls
> +            Database.SaveResult accErrorList2 = Database.update(account4,false);
yes it is possible i will do same.

2022-04-28 17:39 UTC, MHigel approved these changes

2022-04-28 17:39 UTC, merged