Feature/om 393
citron-hygiene-lp/salesforce pull request #53
Opened 2022-04-27 13:10 UTC by Citronhariom

Description : Build has been completed for the OM-393

2022-04-28 12:11 UTC, MHigel requested changes

2022-04-28 12:11 UTC, MHigel commented on force-app/main/default/classes/OpportunityValidationWrapperTest.cls
> +        System.runAs(new User(Id = UserInfo.getUserId())) {
This code will always execute as the running user, so using `System.runAs` here doesn't change the test's behavior.

2022-04-28 12:11 UTC, MHigel commented on force-app/main/default/classes/OpportunityValidationWrapperTest.cls
> +        test.stopTest();
This test has no asserts to validate the output.

2022-04-29 14:57 UTC, MHigel requested changes

2022-04-29 14:57 UTC, MHigel commented on force-app/main/default/classes/OpportunityValidationWrapperTest.cls
> +        test.stopTest();
@Citron-mohammad-Rafi this comment is still outstanding.

2022-04-29 18:00 UTC, Citronhariom commented on force-app/main/default/classes/OpportunityValidationWrapperTest.cls
> +        test.stopTest();
Hi @MHigel,
I have updated My PR , Please review it once and let me know if any changes required  .

2022-05-02 13:31 UTC, MHigel requested changes

2022-05-05 13:12 UTC, closed without merging