Feature/om 184
citron-hygiene-lp/salesforce pull request #57
Opened 2022-04-28 11:54 UTC by Citronhariom

Descriptions : Build has been completed for the related story OM-184 and OM-410

2022-04-28 12:03 UTC, MHigel requested changes

2022-04-28 12:03 UTC, MHigel commented on force-app/main/default/classes/OpportunityValidationWrapperTest.cls
> +        System.runAs(new User(Id = UserInfo.getUserId())) {
Why are we doing this?  This code will always run as the running user, so using `System.runAs` doesn't really change the behavior, right?

2022-04-28 12:03 UTC, MHigel commented on force-app/main/default/classes/OpportunityValidationWrapperTest.cls
> +        insert opp1;
We should combine the insert DML of these opps into a single DML using a collection.

2022-04-28 12:03 UTC, MHigel commented on force-app/main/default/classes/OpportunityValidationWrapperTest.cls
> +    static testMethod void validateOpportunitiesBeforeInsertMethod() {
There are no asserts in this test, so we have no way of validating whether the tested functionality actually works.  Those asserts must validate the expected outputs and behaviors.

2022-05-12 12:06 UTC, Citronhariom commented
This PR got multiple wrong commit , So creating new PR for the user story om-393

2022-05-12 12:06 UTC, closed without merging