Feature/om 388
citron-hygiene-lp/salesforce pull request #76
Opened 2022-05-04 18:06 UTC by Citronhariom

Descriptions : Build completed for the OM-388

2022-05-05 13:53 UTC, MHigel requested changes

2022-05-05 13:53 UTC, MHigel commented on force-app/main/default/classes/ManageRelatedContactFieldsTest.cls
> +         test.stopTest();
`Test.stopTest()` should occur after the DML, but before any query to retrieve the data being validated.

2022-05-05 13:53 UTC, MHigel commented on force-app/main/default/classes/OpportunityValidationWrapperTest.cls
> +            insert acc;
The Account's `Subsidiary__c` is assigned by using its `RecordType`.  We need to create a `List<Account>` that has Account records for each record type, then create the necessary related records for each Account.  The test should validate that the process works for Opportunity records whose `Subsidiary__c` value is "CA", and does not execute for records whose `Subsidiary__c` value is either "US" or "UK".

2022-05-05 13:53 UTC, MHigel commented on force-app/main/default/classes/OpportunityValidationWrapperTest.cls
> +            system.assert(ocr.IsPrimary == false);
This is not a valid test.  The code being tested is not responsible for validating the setting of the `IsPrimary` field.  The test should validate the functionality being executed.

2022-05-05 13:53 UTC, MHigel commented on force-app/main/default/classes/OpportunityValidationWrapperTest.cls
> +           test.stopTest();
If the tested code fires after update, then we need to validate the output of that update.  We have to re=query for the records, and include asserts that validate the results.

2022-05-12 11:55 UTC, closed without merging

2022-05-12 11:56 UTC, Citronhariom commented
This Pr has multiple issue ,so created new PR - https://github.com/citron-hygiene-lp/salesforce/pull/136/files#diff-06e5d8a8cc576c55697c34d965f25210c79097419b5b7c7ce7a08921de24bcac