om-440
citron-hygiene-lp/salesforce pull request #87
Opened 2022-05-06 17:07 UTC by sidhartha-citron

2022-05-07 16:24 UTC, MHigel reviewed
@sidhartha-citron I'm seeing a lot of changes here unrelated to the requirements in OM-440.  Can you verify that all of the items being removed from this Workflow are correct?

2022-05-09 11:25 UTC, sidhartha-citron commented
Added all the workflowrules for Opportunity. Before i was adding only the new Workflow rule which got created. Seems it is overriding and removing other rules which it should be appending not removing. Now i have added all the rules.

2022-05-09 21:41 UTC, MHigel requested changes

2022-05-09 21:41 UTC, MHigel commented on force-app/main/default/workflows/Opportunity.workflow-meta.xml
> +        <formula>Account.Name &amp; &quot; - &quot; &amp;  TEXT(Opportunity_Type__c) &amp; &quot; - &quot; &amp; TEXT(CloseDate)</formula>
This commit will revert changes done to the formula that incorporates the `Subsidiary__c` value:

```<formula>AND(   ISPICKVAL(StageName, &apos;Signed&apos;) ,   ISPICKVAL( Processing_Status__c ,&apos;Completed&apos;),ISPICKVAL( Account.Subsidiary__c  , &apos;CA&apos;) )</formula>```

2022-05-10 09:54 UTC, sidhartha-citron commented on force-app/main/default/workflows/Opportunity.workflow-meta.xml
> +        <formula>Account.Name &amp; &quot; - &quot; &amp;  TEXT(Opportunity_Type__c) &amp; &quot; - &quot; &amp; TEXT(CloseDate)</formula>
This is fixed now. Added Update Account Type Workflow Rule

2022-05-10 22:31 UTC, MHigel approved these changes

2022-05-10 22:33 UTC, merged